const searchTypes = {
  CHANGE_SEARCH_VAL: "CHANGE_SEARCH_VAL",
  SEND_SEARCH_START: "SEND_SEARCH_START",
  SEND_SEARCH_SUCCESS: "SEND_SEARCH_SUCCESS",
  SEND_SEARCH_FAILED: " SEND_SEARCH_FAILED",
  SEND_SEARCH_CLEAR: " SEND_SEARCH_CLEAR",
};

export default searchTypes;
