const MostPopularTypes = {
  GET_MOST_POPULAR_START: " GET_MOST_POPULAR_START",
  GET_MOST_POPULAR_SUCCESS: "GET_MOST_POPULAR_SUCCESS",
  GET_MOST_POPULAR_FAILED: "GET_MOST_POPULAR_FAILED",
};

export default MostPopularTypes;
